### ISSUE TITLE
Rule suggestion: no-promise-executor-return

### ISSUE THREAD

**Issue by NemoStein** [standard/standard#1561] opened 2020-10-23 07:46 UTC
Returning inside a promise executor is most certainly an error as the return value cannot be used.
Since Standard 15 comes with ESLint v7, the `no-promise-executor-return` rule could be added.

**Comment by feross** [comment] 2020-10-23 18:33
Duplicate of https://github.com/standard/standard/issues/1555

**Closed by feross** 2020-10-23 18:33 UTC
