### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by satya1990** [standard/standard#882] opened 2017-05-11 01:43 UTC
I was trying set up standard for mocha.
$standard --env mocha
I'm getting the following error logs on console.
Error:
standard: Unexpected linter output:
RangeError: Maximum call stack size exceeded
logs:
    at Array.values (native)
    at findVariable (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:141:42)
    at findVariable (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:145:24)
    at checkDestructuring (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:299:34)
    at checkProperties (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:373:21)
    at checkVariable (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)
    at checkDestructuring (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:301:21)
    at checkProperties (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:386:21)
    at checkVariable (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)
    at checkDestructuring (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:301:21)

**Comment by Sullux** [comment] 2017-05-18 19:23
I'm getting the same thing:

```
RangeError: Maximum call stack size exceeded
    at findVariable (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:141:40)
    at findVariable (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:145:24)
    at checkDestructuring (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:299:34)
    at checkProperties (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:373:21)
    at checkVariable (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)
    at checkDestructuring (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:301:21)
    at checkProperties (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:373:21)
    at checkVariable (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)
    at checkDestructuring (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:301:21)
    at checkProperties (/usr/local/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:373:21)
```

This is only happening on one project. Other projects on the same system seem to lint fine.

**Comment by landon9720** [comment] 2017-05-26 14:54
Same thing here. `npm install standard --global; standard` ... `RangeError` etc.

**Comment by rajat1saxena** [comment] 2017-06-02 17:54
Same here as well

**Comment by gingermusketeer** [comment] 2017-06-21 08:56
I was saw this problem on a project I am working on as well with version `10.0.2` of standard on OSX `10.12.5`. The error message was
```
standard: Unexpected linter output:

RangeError: Maximum call stack size exceeded
    at inspect (util.js:168:13)
    at exports.format (util.js:69:24)
    at Console.log (console.js:43:37)
    at findVariable (/project-folder/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:139:13)
    at findVariable (/project-folder/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:147:24)
    at checkDestructuring (/project-folder/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:302:34)
    at checkProperties (/project-folder/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:376:21)
    at checkVariable (/project-folder/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:407:13)
    at checkDestructuring (/project-folder/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:304:21)
    at checkProperties (/project-folder/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:389:21)

```

After adding some debugging information to `node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js` so that I could see the file that was being checked I discovered that I had a nested folder with node_modules in it that appeared to be being checked by eslint. The path was something like `/project-folder/nested-folder/node_modules/babel-jest/build/index.js`.

Not sure if this is the actual problem or if I was just lucky that removing this unneeded folder solved my issue.

**Comment by vramana** [comment] 2017-07-07 15:16
I see the same issue on npm repo reproduced via travis https://travis-ci.org/npm/npm/jobs/251196118

**Comment by luispabon** [comment] 2017-07-18 12:30
Same here on Linux, npm 5.0.3, standard 10.0.2 and eslint-plugin-node 4.2.2

**Comment by tunnckoCore** [comment] 2017-07-18 12:42
https://github.com/standard/standard/issues/933

**Comment by tunnckoCore** [comment] 2017-07-18 12:44
@vramana, @luispabon, @gingermusketeer i may help if post some files, or part of the files :)

**Comment by vramana** [comment] 2017-07-18 13:41
@tunnckoCore You can reproduce it with npm latest branch. The error triggers on Travis, so you can use Travis if you can't reproduce it on your machine.

**Comment by luispabon** [comment] 2017-07-18 14:05
Okay, the empty project was somehow picking a file on the parent folder containing some dodgy code I reckon standard is looping through forever. I've managed to distill it all down to:
```javascript
let fs = fs || require('fs')
```
Steps to reproduce:
 1) make a folder somewhere
 2) make a .js file containing the code above
 2) run `npm install standard`
 4) run `node_modules/.bin/standard`
 5) Profit!

It seems specific to the `fs` component though.

**Comment by tunnckoCore** [comment] 2017-07-19 10:34
Now we can close this, @ematipico :) v4.2.3 is released by @mysticatea! :tada:

**Comment by Flet** [comment] 2017-11-07 00:15
Cool, if folks are having issues still, reinstall `standard` and it should pull the the fix down :)

**Closed by Flet** 2017-11-07 00:15 UTC
