### ISSUE TITLE
Failed to load plugin 'import' declared in '--config » eslint-config-standard': Cannot find module 'eslint'

### ISSUE THREAD

**Issue by marcospgp** [standard/standard#1439] opened 2019-10-14 12:27 UTC
> Failed to load plugin 'import' declared in '--config » eslint-config-standard': Cannot find module 'eslint'

Should I install eslint? Couldn't find this information in the readme.

Thanks!

**Comment by mightyiam** [comment] 2019-10-14 12:36
Hi, @marcospgp. Thank you for using Standard. To begin helping you, I'd like more information. Could you please submit a new issue with all of the issue template filled in? For our convenience, I'll close this one.

**Comment by marcospgp** [comment] 2019-10-14 12:40
@mightyiam I'm sorry, I don't have the time right now. I just installed standard so it's the latest version. Ran on VSCode on Windows. Standard is the only project dependency.

**Comment by mightyiam** [comment] 2019-10-14 12:49
Could you please run `npm --version` and `node --version` and paste the results here?

**Comment by marcospgp** [comment] 2019-10-14 13:19
For sure! 

```
$ npm --version
6.11.3

$ node --version
v10.16.0
```

**Comment by mightyiam** [comment] 2019-10-14 13:22
How are you running `standard`, please? Is it via the command line in VSCode or via some extension?

**Comment by marcospgp** [comment] 2019-10-14 13:42
I tried both with the integrated command line in VSCode (bash) and through the VSCode extension, both show the same error. No problem!

**Comment by mightyiam** [comment] 2019-10-14 13:51
Could you please paste the result of the `npm ls eslint` command?

**Comment by LinusU** [comment] 2019-10-15 08:34
I have this consistently failing on Travis CI! 😄 

https://travis-ci.org/LinusU/node-albatross/jobs/597540373

```sh
$ node --version
v12.12.0
$ npm --version
6.11.3
```

```text
standard: Unexpected linter output:

Error: Failed to load plugin 'import' declared in '--config » eslint-config-standard': Cannot find module 'eslint'
Require stack:
- /home/travis/build/LinusU/node-albatross/node_modules/eslint-plugin-import/lib/ExportMap.js
- /home/travis/build/LinusU/node-albatross/node_modules/eslint-plugin-import/lib/rules/named.js
- /home/travis/build/LinusU/node-albatross/node_modules/eslint-plugin-import/lib/index.js
- /home/travis/build/LinusU/node-albatross/node_modules/standard/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /home/travis/build/LinusU/node-albatross/node_modules/standard/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /home/travis/build/LinusU/node-albatross/node_modules/standard/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/travis/build/LinusU/node-albatross/node_modules/standard/node_modules/eslint/lib/cli-engine/index.js
- /home/travis/build/LinusU/node-albatross/node_modules/standard/node_modules/eslint/lib/api.js
- /home/travis/build/LinusU/node-albatross/node_modules/standard/options.js
- /home/travis/build/LinusU/node-albatross/node_modules/standard/bin/cmd.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/travis/build/LinusU/node-albatross/node_modules/eslint-plugin-import/lib/ExportMap.js:20:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
```

I wonder if the problem is that `eslint` isn't getting hoisted up, and thus the other modules can't find it? Since it's only required by `standard`:

```sh
$ npm ls eslint          
albatross@1.1.0 /Users/linus/coding/node-albatross
└─┬ standard@14.3.1
  └── eslint@6.4.0 
```

**Comment by LinusU** [comment] 2019-10-15 08:37
Hmm, maybe this is related?

> This `@npmjs` bug randomly makes ESLint installation fail when a package which has a name alphabetically before 'eslint' depends on an older version of 'acorn' https://github.com/eslint/espree/issues/393 …

https://twitter.com/feross/status/1161900081492234240

Not exactly the same though? 🤔

**Comment by LinusU** [comment] 2019-10-15 08:41
This makes it seem like `npm` is simply not installing `eslint` package though 🤔 

```text
npm WARN eslint-config-standard@14.1.0 requires a peer of eslint@>=6.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard-jsx@8.1.0 requires a peer of eslint@>=6.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-es@2.0.0 requires a peer of eslint@>=4.19.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.18.2 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@10.0.0 requires a peer of eslint@>=5.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.14.3 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-standard@4.0.1 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by mightyiam** [comment] 2019-10-19 04:55
@LinusU, if you have a local installation where this is occurring, could you please type in `npm ls eslint` to see if and where it is I stalled?

**Comment by LinusU** [comment] 2019-10-26 13:12
Unfortunately, I haven't been able to reproduce this locally yet. Hopefully I can take some time soon to reproduce this inside an Ubuntu Docker container ☺️

**Comment by LinusU** [comment] 2019-11-13 19:05
This seems to be fixed with all the latest versions now.

@marcospgp can you try and trash your `node_modules/` and `package-lock.json`, then install again and see if it works? Happy to re-open if you are still having problems!

**Closed by LinusU** 2019-11-13 19:05 UTC

**Comment by AndyOGo** [comment] 2019-12-08 19:29
I just got the same error, turns out `standard` was upgraded in `package.json`, but a local `package-lock.json` (was wasn't commit and in gitignore file), caused it that another version was used...

**Comment by mightyiam** [comment] 2019-12-09 04:16
Thank you for the tip, @AndyOGo .

**Comment by prateekrastogi** [comment] 2020-02-20 16:34
@AndyOGo Worked pretty well for me too

**Comment by Fuzzyma** [comment] 2020-06-19 00:37
I have the same error but only when I want to use it with VSCode. The ESLint tab shows this:

```
[Info  - 10:30:15] ESLint server stopped.
[Info  - 10:30:15] ESLint server running in node v12.8.1
[Info  - 10:30:15] ESLint server is running.
[Info  - 10:30:18] ESLint library loaded from: <path>\root\node_modules\eslint\lib\api.js
[Error - 10:30:19] 
Failed to load plugin 'import' declared in '<path>\root\.eslintrc.js » eslint-config-standard': Cannot find module 'eslint-plugin-import'
Require stack:
- <path>\__placeholder__.js
Happened while validating <path>\root\.eslintrc.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-import' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-import' isn't installed correctly.

Consider running eslint --debug <path>\root\.eslintrc.js from a terminal to obtain a trace about the configuration files used.
```

The require stack is a bit strange because it starts from the project root and not from the eslint root.

**Comment by Fuzzyma** [comment] 2020-06-19 22:09
Ok for VSCode try this solution in case your eslint root is not your project root: https://github.com/microsoft/vscode-eslint/issues/196
