### ISSUE TITLE
spaced-comment on ///

### ISSUE THREAD

**Issue by jackens** [standard/standard#1389] opened 2019-08-26 07:32 UTC
**What version of this package are you using?**

11.0.1

**What operating system, Node.js, and npm version?**

OS: Windows 10, Node.js: v12.9.0, npm: 6.10.2

**What happened?**

```js
/// This is some documentation comment
///
/// File: `foo.js`
function foo () { }

foo('bar')

```

Running

```bash
standard --fix -v foo.js
```

generates

```
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  C:\Users\jackens\git\foo.js:2:1: Expected space or tab after '///' in comment. (spaced-comment)
```

**What did you expect to happen?**

No `spaced-comment` errors for

```
///
```

**Are you willing to submit a pull request to fix this bug?**

Nope

**Comment by jackens** [comment] 2019-08-26 18:38
Please check `spaced-comment` explanation at <https://eslint.org/docs/rules/spaced-comment>:

> […]
> The `"markers"` value is an array of string patterns which are considered markers for docblock-style comments, such as an additional `/` documentation read by doxygen, vsdoc, etc. which must have additional characters.
> […]

The problem is, that requires following configuration:

```json
{
  "spaced-comment": ["error", "always", { "markers": ["/"], "exceptions": ["/"] }]
}
```

instead of:

```json
{
  "spaced-comment": ["error", "always", { "markers": ["/"] }]
}
```

Writing

```js
/* eslint spaced-comment: ["error", "always", { "markers": ["/"], "exceptions": ["/"] }] */

/// This is some documentation comment
///
/// File: `foo.js`
function foo () { }

foo('bar')
```

is quite ugly

**Comment by feross** [comment] 2020-10-31 04:33
I can't reproduce this issue anymore on `standard` 16 so it appears to have been fixed.

Specifically, it appears to have been fixed in `standard` 14.

```bash
npx standard@14 --verbose foo.js
```

returns nothing

**Closed by feross** 2020-10-31 04:33 UTC
