### ISSUE TITLE
Issue with indentation of expressions in ternary expression

### ISSUE THREAD

**Issue by sheerun** [standard/standard#1451] opened 2019-11-07 10:11 UTC
This relates to https://github.com/sheerun/prettier-standard/issues/76

functions are normally formatted with indentation which looks nice:

```es6
commission => {
  return suggestions.hits.map(hit => something(hit))
}
```

but when trenary expression is used it doesn't have it:

```es6
search.premium
  ? commission => {
    return suggestions.hits.map(hit => something(hit))
  }
  : () => onOpen()
```

It seems to me that while having indentation of each level of `?:` is great decision, the less great decision is that indentation is at the level of `?` itself instead of at the level of of expression after `?` (this doesn't prevent expressions being indented for each level of `?:`):

```es6
search.premium
  ? commission => {
      return suggestions.hits.map(hit => something(hit))
    }
  : () => onOpen()
```

---

Here's an example with multi-level `?:`. That's how it is currently:

```es6
search.premium
  ? commission => {
    return suggestions.hits.map(hit => something(hit))
  }
  : something
    ? commission => {
      return suggestions.hits.map(hit => something(hit))
    }
    : null
```

That's what I think it should be:

```es6
search.premium
  ? commission => {
      return suggestions.hits.map(hit => something(hit))
    }
  : something
    ? commission => {
        return suggestions.hits.map(hit => something(hit))
      }
    : null
```

--- 

Another example what it is currently:

```es6
search.premium
  ? somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething &&
  somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething
  : something
    ? somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething &&
    somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething
    : null
```

And what it probably should be:

```es6
search.premium
  ? somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething &&
    somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething
  : something
    ? somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething &&
      somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething
    : null
```

And here's what prettier currently does (plese notice that `?:` is at the same level, but **also** indentation of expression is at the same level as `something...` and not `?`:

```es6
search.premium
  ? somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething &&
    somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething
  : something
  ? somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething &&
    somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething
  : null
```

You might say the same "bug" in prettier would look like this:

```es6
search.premium
  ? somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething &&
  somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething
  : something
  ? somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething &&
  somethingsomethingsomethingsomethingsomethingsomethingsomethingsomething
  : null
```

**Comment by mightyiam** [comment] 2019-11-11 07:30
@sheerun thank you for your interest and detailed report.

Feel to me like this should be discussed upstream, ESLint. Is there an issue for this there?

**Comment by mightyiam** [comment] 2019-11-11 07:31
I totally agree. I am using many ternaries and this bothers me, as well.

**Comment by mightyiam** [comment] 2019-11-11 07:33
Seems like a duplicate of #927, doesn't it? If I'm wrong, please tell me.

**Closed by mightyiam** 2019-11-11 07:33 UTC
