### ISSUE TITLE
standard 14 reports parsing errors for valid public static class fields

### ISSUE THREAD

**Issue by zeke** [standard/standard#1524] opened 2020-05-25 05:05 UTC
**What version of this package are you using?**

14.3.4

**What operating system, Node.js, and npm version?**

macOS Catalina, Node.js 12.8.0, npm 6.14.3

**What happened?**

This is a repeat of https://github.com/standard/standard/issues/940 where the use of a [public static class field](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields#Public_fields):

```js
class ClassWithStaticField {
  static staticField = 'static field'
}
```

Causes this error:

```
Parsing error: Unexpected token =
```

Repros:

- https://runkit.com/zeke/5ecb2dadd71fee001b140d56
- https://github.com/zeke/standard-class-static-props

**What did you expect to happen?**

I do not expect to see any errors.

**Are you willing to submit a pull request to fix this bug?**

Perhaps!?

**Comment by zeke** [comment] 2020-05-25 05:10
It appears that eslint comments don't work as a workaround for this either:

```js
class AlgoliaIndex {
  static maxRecordLength = 8000 // eslint-disable-line
}
```

still causes this error:

```
> standard --fix

standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/z/git/github/docs/lib/algolia/search-index.js:12:27: Parsing error: Unexpected token =
```

**Comment by pal** [comment] 2020-10-26 19:22
Did you find a work-around @zeke?

**Comment by feross** [comment] 2020-10-27 04:15
[Static class features](https://github.com/tc39/proposal-static-class-features) is still Stage 3 and it's ESLint policy to only support Stage 4 proposals.

In the meantime, you can enable support with `babel-eslint` by following the instructions here: https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features

Also, duplicate of https://github.com/standard/standard/issues/1478

**Closed by feross** 2020-10-27 04:15 UTC

**Comment by balazsorban44** [comment] 2021-03-01 23:50
Trying to add support for this Stage 3 proposal.

@feross Tried using the [How do I use experimental JavaScript (ES Next) features?](https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features) section, and added the following to my `package.json`:

```json
"standard": {
  "parser": "@babel/eslint-parser"
}
```

Running `npx standard file.js` reports the following error:
> standard: Use JavaScript Standard Style (https://standardjs.com)
  /project/file.js:0:0: Parsing error: No Babel config file detected for /project/file.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.

Tried also adding the config to `package.json` like the following [as per the docs for @babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser#additional-parser-configuration):

```json 
"standard": {
  "parser": "@babel/eslint-parser",
    "parserOptions": {
      "babelOptions": {
        "configFile": "./config/babel.config.json"
      }
    }
  }
}
```

**Comment by RangerMauve** [comment] 2021-09-03 18:18
I noticed that there's new rules being added to eslint that support this functionality.

https://github.com/eslint/eslint/pull/14591

Would updating the eslint dependency in standard be enough to enable the parsing?

Do we need to wait for all the private rules to be finished before it gets added into standard, or would the partial set that's already complete be enough?

**Comment by RangerMauve** [comment] 2021-09-03 18:20
Ah, looks like the new features are in eslint@8.0.0-beta.1, so I'm guessing we'd need to wait for the next stable version to be released.
