### ISSUE TITLE
Support JSON linting or provide best practice for using with JSON.

### ISSUE THREAD

**Issue by wcatron** [standard/standard#1463] opened 2019-12-09 13:22 UTC
**What version of this package are you using?**
13.0.2

**What problem do you want to solve?**
Linting the many `json` config files being used in my project. Including but not limited to `tsconfig.json` and `package.json`. Currently linting a json file suggests single quotes for everything which is very much non-standard. I think is #788 was on to something but framed their question all wrong. It's not that standard isn't in line with ECMAScript, it's just that it doesn't support json. imho it should :)

**What do you think is the correct solution to this problem?**
Out of the box support `json` files, no plugins necessary. Or a plugin! I had difficulty finding one in my searching but perhaps that's the proper solution here.

**Are you willing to submit a pull request to implement this change?**
A bit of a learning curve. But if someone believed this would be accepted and could point me in the direction of how to implement this, I would be willing to.

**Comment by mightyiam** [comment] 2019-12-10 09:49
Thank you @wcatron for your suggestion.

Seems like a duplicate of #903.

**Closed by mightyiam** 2019-12-10 09:49 UTC
