### ISSUE TITLE
Parsing error: couldn't resolve `eslint` babel-eslint@8.1.2

### ISSUE THREAD

**Issue by joshuaalpuerto** [standard/standard#1035] opened 2017-12-27 04:47 UTC
Hi am not sure if this issue goes here. But when im running test on my CI its failing due to:

<img width="714" alt="screen shot 2017-12-27 at 12 44 16 pm" src="https://user-images.githubusercontent.com/7126484/34370949-b4b68c80-eb03-11e7-86c1-c2fc6088dce6.png">

**standard@10.0.3**
**babel-eslint@8.1.2**

I have to revert back to **babel-eslint@8.0.3** to make my test pass.

Cheers!

**Comment by timoxley** [comment] 2017-12-30 17:00
I'm seeing a similar issue. Using `babel-eslint@8.1.2` my editor (`vim` + `ALE`) reports "x is not defined" for class fields (static and instance).  I get the same error running `standard` on the command line:

```
npx standard …/components/View3D.js
standard: Use JavaScript Standard Style (https://standardjs.com)
  …/View3D/index.js:6:10: 'propTypes' is not defined.
  …/View3D.js:10:3: 'viewConfig' is not defined.
```
Note this is a different error to not having any "standard.parser" value set in `package.json`.

After installing `babel-eslint@8.0.3` and the issue goes away.

Something definitely up with `babel-eslint@8.1.2`.

**Comment by Ukrai** [comment] 2018-01-02 12:32
Unlock my iCloud!

**Comment by doodlewind** [comment] 2018-01-06 01:09
Possible same issue raised in `babel-eslint`
https://github.com/babel/babel-eslint/issues/564

**Comment by doodlewind** [comment] 2018-01-06 02:32
I investigate a bit and found that a patch for scope analysis is introduced in #542, which is [not compatible](https://github.com/babel/babel-eslint/pull/542#issuecomment-353943499) with `babel-eslint@7.x`. Since `standard@10.x` uses `babel-eslint@7.x`, this patch may introduce unexpected behaviors for `standard@10.x`.

The good news is that in `standard@11.x`, dependency version is updated to `babel-eslint@8.x`. I've tested several permutation and find two workarounds for now:

1. Install `standard@10.x` with `babel-eslint@7.x`
2. Install `standard@11.x` with `babel-eslint@8.x`

Any ideas fixing `standard@10.x` with `babel-eslint@8.x`, or warn user in this case?

**Comment by GBarkhatov** [comment] 2018-01-06 03:33
Using babel-eslint@8.0.3 works fine, spend a day solving this.

**Comment by pex** [comment] 2018-01-10 13:11
As described in https://github.com/babel/babel-eslint/issues/564#issuecomment-356329556 this issue is not limited to `standard` but also to [`XO`](https://github.com/sindresorhus/xo).

**Comment by ematipico** [comment] 2018-01-10 14:49
Thanks @pex for your comment!
Closing the issue as it's not a problem of `standard` but of  `babel-eslint@8.1.3`. A temporary solution is to downgrade to `babel-eslint@8.0.3`

**Closed by ematipico** 2018-01-10 14:49 UTC
