### ISSUE TITLE
standard v14 not working with files in a different directory

### ISSUE THREAD

**Issue by revington** [standard/standard#1384] opened 2019-08-21 18:39 UTC
**What version of this package are you using?**
14.0.0
**What operating system, Node.js, and npm version?**
Void Linux, node 10.16.3, npm 6.9.0
**What happened?**
`$ standard --fix $file-not-same-directory` fails with 
```
/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/deglob/node_modules/ignore/index.js:337
  throw new Ctor(message)
  ^

RangeError: path should be a `path.relative()`d string, but got "../../tmp/crap.js"
    at throwError (/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/deglob/node_modules/ignore/index.js:337:9)
    at checkPath (/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/deglob/node_modules/ignore/index.js:356:12)
    at Ignore._test (/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/deglob/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/deglob/node_modules/ignore/index.js:512:17)
    at path (/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/deglob/node_modules/ignore/index.js:516:26)
    at Array.filter (<anonymous>)
    at Ignore.filter (/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/deglob/node_modules/ignore/index.js:520:29)
    at /home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/deglob/index.js:46:31
    at end (/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/run-parallel/index.js:18:15)
    at done (/home/pedro/.nvm/versions/node/v10.16.3/lib/node_modules/standard/node_modules/run-parallel/index.js:22:10)

```
but `$ standard --fix file.js ` works as expected

**Comment by revington** [comment] 2019-08-22 07:33
I have the same error with standard@13 but not with standard@12

**Comment by theimpostor** [comment] 2019-09-03 17:44
I am seeing this error as well on macos with node@10 via homebrew:

```
~ node --version
v10.16.3
~ npm --version
6.11.2
~ standard --version
14.1.0
~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G8030
```

**Comment by feross** [comment] 2019-09-11 01:02
Can you run `npm ls ignore` and report the output?

**Comment by theimpostor** [comment] 2019-09-11 14:55
```
~ npm ls -g ignore
/usr/local/lib
└─┬ standard@14.1.0
  ├─┬ eslint@6.2.2
  │ └── ignore@4.0.6 
  ├─┬ eslint-plugin-node@9.1.0
  │ └── ignore@5.1.4 
  └─┬ standard-engine@12.0.0
    └─┬ deglob@4.0.1
      └── ignore@5.1.4 
```

**Comment by revington** [comment] 2019-09-11 18:51
I'm on holidays until September 23rd. I'll get back to this as soon as I'm
back

**Comment by revington** [comment] 2019-09-11 18:52
AFAIK this problem is related to dep. Ignore

**Comment by theimpostor** [comment] 2019-09-11 19:37
In my case I am using standard installed via 'npm install -g standard'.
Here is the command ALE is running and getting an error back:

(finished - exit code 1) ['/usr/local/bin/bash', '-c', '''standard'' --fix
''/var/folders/mk/_gnvhfnn339_pqkx_7m8m5200000gp/T/nvimfeWbPA/6/index.js''']

**Comment by feross** [comment] 2019-09-11 19:55
Thanks. Just a few more questions:

- Do you have a "standard" option in your `package.json` file? If yes, can you paste it here?
- Do you have a `.gitignore` file in your project? If yes, can you paste it here?

**Comment by zwx00** [comment] 2019-11-09 18:30
This is still broken.

**Comment by mightyiam** [comment] 2019-11-11 09:25
@feross were you able to reproduce, please?

**Comment by coreybutler** [comment] 2019-12-18 04:12
@feross - I came across this running `standard "../src/**/*.js" --verbose`. It seems standard cannot accept relative paths using dot notation. Is that intentional?

For context, I have a complex build & test environment. I've abstracted the build/test aspects into their own local modules. My project structure looks like this:

```
root
  /src
    files.js
  /build
    node_modules
    package.json
  /test
    node_modules
    package.json  <-- This is where npm script runs standard
```

I'm running standard as part of an npm script within the `test` directory.

_If Standard isn't supposed to support this_, no worries (consider this a feature request). If it is supposed to support this, the issue stems from [ignore/index.js#354](https://github.com/kaelzhang/node-ignore/blob/master/index.js#L354), where the regex is marking these relative paths as invalid.

For what it's worth, I changed that line to the following (reverse the checkPath):

![image](https://user-images.githubusercontent.com/770982/71054860-1ba63d80-2119-11ea-82d6-23f369286767.png)

Doing that, all worked as expected, despite the quick hack and zero impact testing. Standard still respected my rather large list of ignore patterns.

**Comment by kpeters-cbsi** [comment] 2020-02-14 18:41
I'm seeing this as well using `standard` 14.3.1. Happens with or without a `.gitignore`

**Comment by DanSchoppe** [comment] 2020-03-07 01:21
A debugging clue...

I worked around this by manually editing `node_modules/deglob/node_modules/ignore/index.js::createFilter()`:
```
  createFilter () {
    return path => true // !this.ignores(path)
  }
```

To be clear, this change worked for both:
- a globally-installed binary, which was failing on `../` relative paths even without any `.gitignore` in the working directory or any parent of the working directory
- a project-installed binary, where there *is* a .gitignore present

Not sure what's leading up to this call to filter, but it seems broken. 🤷‍♂

**Comment by feross** [comment] 2020-10-29 00:27
I can no longer reproduce this issue, so perhaps it was fixed upstream in `ignore`? In either case, we're removing `deglob` (which was invoking `ignore`) in the next version of `standard`, v16.

So, this issue should be fixed!

**Closed** 2020-10-29 01:06 UTC
Labels: accepted, bug

**Comment by feross** [comment] 2020-10-29 01:20
This will be fixed in `standard` 16
