### ISSUE TITLE
merge `prettier` to `eslint`, like `jscs`

### ISSUE THREAD

**Issue by le93us** [standard/standard#1059] opened 2018-02-04 09:13 UTC
Hello,

1. long time ago there was [`jscs`](http://jscs.info/) project, merged to `eslint`
2. `eslint` and `babel` use the same [`acorn.js`](https://github.com/acornjs/acorn) parser

It will be great, if `prettier` will be merged to `eslint` and after `eslint` merged to `babel` toolchain.

So, what use think about working with `eslint` team together?

**Comment by eddiemonge** [comment] 2018-02-07 19:34
duplicate of https://github.com/standard/standard/issues/811 ?

**Closed** 2018-02-07 22:42 UTC
