### ISSUE TITLE
Unexpected linter output

### ISSUE THREAD

**Issue by michaelnisi** [standard/standard#950] opened 2017-07-12 15:52 UTC
Today, trying the latest and greatest: Node v8.1.3, npm 5.2.0, standard 10.0.2, I got `standard: Unexpected linter output`, while running standard via npm pretest script. This might as well be a npm issue, but I decided to put it here first. Running standard alone works as expected, local and global versions of standard are 10.0.2.

```js
  "scripts": {
    "pretest": "standard", ...
```

This never failed me, but today, after updating npm and standard, I got:

```
± % npm test                                                                                                                                                      !10018

> pickup@5.1.1 pretest /Users/michael/workspace/pickup
> standard

standard: Unexpected linter output:

Error: Failed to load plugin import: Cannot find module 'eslint-plugin-import'
Referenced from: /Users/michael/workspace/pickup/node_modules/standard/eslintrc.json
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.load (/Users/michael/workspace/pickup/node_modules/eslint/lib/config/plugins.js:134:29)
    at Array.forEach (native)
    at Object.loadAll (/Users/michael/workspace/pickup/node_modules/eslint/lib/config/plugins.js:162:21)
    at load (/Users/michael/workspace/pickup/node_modules/eslint/lib/config/config-file.js:541:21)
    at configExtends.reduceRight (/Users/michael/workspace/pickup/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/michael/workspace/pickup/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/Users/michael/workspace/pickup/node_modules/eslint/lib/config/config-file.js:566:22)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
npm ERR! Test failed.  See above for more details.
```

**Comment by michaelnisi** [comment] 2017-07-12 16:10
Pointing pretest into node_modules doesn’t make a difference, resulting in the same error.

```js
 "scripts": {
    "pretest": "./node_modules/standard/bin/cmd.js", ...
```

**Comment by LinusU** [comment] 2017-07-12 16:30
> This was a [breaking change](https://github.com/npm/npm/pull/17678) in npm v5.2.0 that has now been [reverted](https://github.com/npm/npm/issues/17717). Use npm v5.1.0 as a workaround until v5.2.1 is available.

Duplicate of #949

**Closed by LinusU** 2017-07-12 16:30 UTC

**Comment by Aladdin-ADD** [comment] 2017-08-19 17:02
I got this error using npm v5.3.0.
