### ISSUE TITLE
Error when using babel-parser in dynamic imports

### ISSUE THREAD

**Issue by falcoagustin** [standard/standard#1041] opened 2018-01-09 11:04 UTC
I'm using `babel-eslint v6.1.2` along with `standard v10.0.3` and I'm not able to bypass the error when doing dynamic imports, this way:

```js
import('path/to/module').then(module => {
  //do Somthing
})
```

It raises ` error  Parsing error: 'import' and 'export' may only appear at the top level`. I tried using:
 
```json
parsingOptions: {
    "AllowImportExportEverywhere": true
}
```
And still raises the error, had to ignore the file instead.

**Comment by ematipico** [comment] 2018-01-09 14:49
I don't it's a `standard` related issue. 
Have a look to this duplicate https://github.com/standard/standard/issues/751

**Comment by falcoagustin** [comment] 2018-01-09 15:10
@ematipico I agree, I should've posted on `babel-eslint`, but I spoke with @feross and told me to raise an issue here, if he confirms I can repost it there 😄

**Comment by feross** [comment] 2018-05-10 01:31
Using `babel-eslint@8` and `standard@11`, I am unable to reproduce this issue. It lints `import()` perfectly fine as far as I can tell.

I'm going to assume that this issue has been fixed in the intervening major version releases.

**Closed by feross** 2018-05-10 01:31 UTC
