### ISSUE TITLE
Is JSX enabled by default?

### ISSUE THREAD

**Issue by waghanza** [standard/standard#1327] opened 2019-07-12 07:39 UTC
**What version of standard?**

`13.01`

**What operating system, Node.js, and npm version?**

Node : `10.16`
Npm : `6.9`
Nvm : `0.34`

**What did you expect to happen?**

I want to check if `javascript` sources respect **standard** default rule. I have not any `jsx` files

**What actually happened?**

`standard` crash saying that no `jsx` files exists
@see https://travis-ci.com/the-benchmarker/web-frameworks/jobs/215413599

**Comment by feross** [comment] 2019-07-12 20:34
There is a bug right now where `standard` doesn't work when installed globally. This is the cause of the issue. I recommend sticking with v12 for now until this issue is fixed.

**Comment by feross** [comment] 2019-07-12 21:21
This should be fixed in `standard` 13.0.2.

**Closed** 2019-07-12 21:22 UTC
Labels: bug
