### ISSUE TITLE
usage of react components not recognized

### ISSUE THREAD

**Issue by rogergl** [standard/standard#872] opened 2017-04-30 15:01 UTC
The following code results in two warnings: React and Article unused. Is this expected ?
```
import React from 'react'
import Article from './components/article/Article'
import PropTypes from 'prop-types'

function ArticleList ({data, itemState}) {
  const listElements = data.map(p => <li key={p.id}><Article data={p.attributes} state={itemState(p.id)}/></li>)
  return (<ul className="results">
    {listElements}
  </ul>)
}

ArticleList.propTypes = {
  data: PropTypes.array,
  itemState: PropTypes.func
}

export default ArticleList

```

**Comment by yoshuawuyts** [comment] 2017-04-30 16:38
It looks like you're using "ArticleList" and not "Article" - also "React"
isn't used anywhere. I think the errors are right here. If for some reason
you need things to be in scope, you can always disable the checks manually
for this instance.

**Comment by rogergl** [comment] 2017-04-30 16:42
No, I'm using Article inside the map and React is required to make things work. It seems that  usages of React components like <Article/> are never recognized.

**Comment by yoshuawuyts** [comment] 2017-04-30 16:53
Oops dang, yeah you're right. Nope, no clue what's up haha. Perhaps someone that uses JSX can help you out (:

**Comment by dyegolara** [comment] 2017-05-09 15:01
It's not necessary to use JSX in React, the issue is on the .js files too

**Comment by hhsadiq** [comment] 2017-08-11 10:28
@rogergl so how you were able to fix that. Want to use standard with react, but unused var errors are becoming blockers.

**Comment by oskarhane** [comment] 2017-08-11 11:19
Use this: https://github.com/standard/eslint-config-standard-jsx

**Comment by Flet** [comment] 2017-12-15 18:52
It looks like this is fixed in the lastest version of `standard`!

Could you give it a try? `npm install standard@beta`

**Comment by feross** [comment] 2018-02-19 22:36
🗣 Standard 11 is released! Run `npm install standard@latest --save-dev` to update to the latest version. This will also update the version in `package.json` ✨

Changelog: https://github.com/standard/standard/releases/tag/v11.0.0

**Closed by feross** 2018-02-19 22:36 UTC
Labels: v11 release
