### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by animsaj** [standard/standard#933] opened 2017-06-25 17:38 UTC
```at RegExp.exec (native)
    at RegExp.test (native)
    at checkProperties (/usr/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:336:31)
    at checkVariable (/usr/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)
    at checkDestructuring (/usr/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:301:21)
    at checkProperties (/usr/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:373:21)
    at checkVariable (/usr/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)
    at checkDestructuring (/usr/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:301:21)
    at checkProperties (/usr/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:386:21)
    at checkVariable (/usr/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)```

**Comment by tunnckoCore** [comment] 2017-07-16 13:02
Same here. @feross, more precise stack

```
% 1 > standard index.js test.js utils.js    
standard: Unexpected linter output:

RangeError: Maximum call stack size exceeded
    at findVariable (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:136:22)
    at findVariable (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:145:24)
    at checkDestructuring (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:299:34)
    at checkProperties (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:386:21)
    at checkVariable (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)
    at checkDestructuring (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:301:21)
    at checkProperties (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:373:21)
    at checkVariable (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:404:13)
    at checkDestructuring (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:301:21)
    at checkProperties (/home/charlike/.nvm/versions/node/v8.1.4/lib/node_modules/standard/node_modules/eslint-plugin-node/lib/rules/no-deprecated-api.js:386:21)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
```

**Comment by tunnckoCore** [comment] 2017-07-16 13:06
Just found that problem comes from `utils.js` I'll look what so bad is happening there ;d

**Comment by tunnckoCore** [comment] 2017-07-16 13:20
Yep. Seems like `lazy-cache` made that problem. Probably `eslint-plugin-node` does something or analyzes the `require`, so it fails.

@animsaj, so if you use some kind of caching mechanism try to remove it and run Standard again. That [was my problem](https://github.com/tunnckoCore/koa-better-body/blob/8d68197ea3af963de1dabf9ce4ecef2b558f9439/utils.js#L7-L36).

**Comment by luispabon** [comment] 2017-07-18 12:44
I don't have lazy-cache on my project though.

**Comment by tunnckoCore** [comment] 2017-07-18 12:46
Yea, probably, but probably the problem is some sort like this, any source may help ;]

**Comment by luispabon** [comment] 2017-07-18 12:47
No source, this happens without a single file to lint.

**Comment by tunnckoCore** [comment] 2017-07-18 12:54
Duh.. ;d Clean cache and reinstall? If you use npm@5+ try `npm cache verify`.

THe whole thing is pretty weird. First issue is published on May 11, last Standard version on April 14, and the plugin on March 28. No changes, no new versions, plus that it is `~` range.

**Comment by luispabon** [comment] 2017-07-18 13:49
Even after!

**Comment by luispabon** [comment] 2017-07-18 13:59
Okay, the empty project was somehow picking a file on the parent folder containing some dodgy code I reckon standard is looping through forever:
```javascript
let fs = fs || require('fs')
```

**Comment by ematipico** [comment] 2017-07-18 14:17
Will close as duplicate of https://github.com/standard/standard/issues/882

**Closed by ematipico** 2017-07-18 14:17 UTC
