### ISSUE TITLE
README outdated? Expressjs is not using this standard, as far as I can see.

### ISSUE THREAD

**Issue by 1602** [standard/standard#1058] opened 2018-02-03 17:46 UTC
Perhaps, readme could be updated in order to not confuse people (not sure maybe they were using it in the past and then decided to use other standard for some reason). I haven't checked other links, but trust maintainers to cleanup other outdated links (if any).

**Comment by dougwilson** [comment] 2018-02-03 18:05
Is this a duplicate of https://github.com/standard/standard/issues/957 ?

**Comment by 1602** [comment] 2018-02-03 19:32
Oops, I missed that one, because it is closed, so it is kind of a duplicate, but bug is still not fixed, not sure why issue #957 closed. As long as .eslint of expressjs is different, it is incorrect to state that project is using this standard, maybe in bright future :)

**Comment by dougwilson** [comment] 2018-02-03 19:39
Yea, like I said in that issue, I'm not sure how the logo got there, but Express rejects all new PRs if they are not in STANDARDJS style. The express project consists of over 40 repos and almost all of them are 100% in StandardJS style. Since I don't know how the logo got here, I don't know if the intent of the logo is to signify Express as the entire project with all it's repos or if it only refers to a very specific, single repo as it seems you're suggesting.

Clicking the logo does not take me to a single repo so it seems to suggest it refers to the project as a while instead of a single repo. I assume if 1 or 2 repos of npm didn't use StandardJS but every one repo did you'd say that npm logo should be removed too?

**Comment by 1602** [comment] 2018-02-04 11:33
If logo leads to a project with standardjs .eslintrc, than it is fine. Not sure about entire organisations, but I'd say not necessary for all the organisation to be following the standard in all legacy projects, which is kind of silly thing to expect, but what seems like a reasonable expectation is that main project has it (which is express in case of expressjs organisation, for example).

**Comment by bcomnes** [comment] 2018-02-04 21:19
I'm going to take @dougwilson's word on this one.

**Closed by bcomnes** 2018-02-04 21:19 UTC
