### ISSUE TITLE
Private instance class field (#fieldname) yields an unexpected character error

### ISSUE THREAD

**Issue by Craphtex** [standard/standard#1401] opened 2019-09-05 09:26 UTC
**What version of this package are you using?**
`14.1.0`

**What operating system, Node.js, and npm version?**
*Operating system*
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
*Node.js*
`12.10.0`

*npm*
`6.11.3`

**What happened?**
I received `Parsing error: Unexpected character '#'` when using the [private instance class field feature, introduced in Node.js v12.4.0](https://node.green/#ESNEXT-candidate--stage-3--instance-class-fields-private-instance-class-fields-basic-support).

**What did you expect to happen?**
As private fields are a good scoping practice, I'd say StandardJS should encourage such usage. Thus I expect no error to be shown.

**Are you willing to submit a pull request to fix this bug?**
With proper introduction to the code base I can consider adding a PR, currently I'm not familiar with neither the StandardJS code base nor the ESLint code base.

**Additional notes**
I assume the underlying issue here is that [ESLint doesn't intend to support the feature until it reaches stage 4](https://github.com/eslint/eslint/issues/11820) (it's currently a stage 3 ESNEXT feature though already supported in Node.js v12.4.0 and onward).

**Comment by feross** [comment] 2019-09-05 19:42
> I assume the underlying issue here is that [ESLint doesn't intend to support the feature until it reaches stage 4](https://github.com/eslint/eslint/issues/11820) (it's currently a stage 3 ESNEXT feature though already supported in Node.js v12.4.0 and onward).

Yep, this is right. Once ESLint adds support, we'll get it in `standard`.

In the meantime, you can follow the instructions to set up babel as your parser if you don't want to wait: https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features

**Comment by feross** [comment] 2019-09-05 19:42
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨

**Closed by feross** 2019-09-05 19:42 UTC

**Comment by Niek** [comment] 2022-04-23 13:11
Standard v17 is based on ESLint 8, but it still complains about private fields. Am I missing something?

**Comment by Divlo** [comment] 2022-04-23 15:02
> Standard v17 is based on ESLint 8, but it still complains about private fields. Am I missing something?

@Niek This should work with Standard v17.
Are you sure you are using the latest Standard v17?
Could you share a small reproducible example/code snippet so we can reproduce it?

**Comment by Niek** [comment] 2022-04-25 09:43
Sorry about this... I found the issue: vscode needs to be reloaded after upgrading Standard to v17. I didn't reload after upgrading, and somehow it kept using v16.
