### ISSUE TITLE
be opinionated about dot chaining indentation

### ISSUE THREAD

**Issue by chee** [standard/standard#974] opened 2017-08-14 08:22 UTC
and perhaps `?:` indentation.

currently, this is accepted by `standard(1)`:

```js
export function opinions () {
  return rad()
.x
        ? 3
  : 1
}
```

which

really this came up because i wasn't sure whether to:

```js
// a: keep level
if (cat) {
 woggle()
 .wiggle(w => {
   return w.x ? w.y : w.z
 })
}
```

or:

```js
// b: indent
if (cat) {
 woggle()
   .wiggle(w => {
     return w.x ? w.y : w.z
   })
}
```

and depending on the particulars of what i'm writing one seems better than the other, but that has left me with some inconsistency in the codebase.

`a` has the upside of the closing braces ending up at the same indentation as the original target of the operation

`b` has the upside of sometimes feeling right

i'm sure i can learn to live with either should this project suggest one

**Comment by chee** [comment] 2017-08-14 08:33
also in favour of `a`:

if you later decide to add a newline before a dot, you don't have to change indentation of its innards.

as in:

```js
expect(a).toEqual({
  type: 'tears',
  number: 99
})
```

becomes:

```js
expect(a)
.toEqual({
  type: 'tears',
  number: 99
})
```

rather than

```js
expect(a)
  .toEqual({
    type: 'tears',
    number: 99
  })
```

**Comment by charlike** [comment] 2017-08-14 15:19
use prettier, period. :D

**Comment by chee** [comment] 2017-08-14 15:36
i mean, fine, but

> The whole point of standard is to save you time by avoiding bikeshedding about code style. 

this is now some code style that i am bikeshedding about.

there are plenty of formatting rules in standard. including that the dot should be on the same line as the property.

as well as `comma-dangle`, `block-spacing`, `comma-style`, `func-call-spacing`, `key-spacing` and so very on.

i mean, you know this, there's no need for me to repeat them here.

`semi-spacing`, `padded-blocks`, `space-in-parens`

there are projects on which i can't use prettier but i would still not like to think about these things

 `space-unary-ops`,  `spaced-comment`(!!!!), `template-curly-spacing`

i'll see what i can do about getting the tech lead to allow me to set up prettier, but the last time i reformatted the entire project he took it thick.

`semi`

(i understand you said "not always true", and i understand your suggestion is probably quite a good one, but it doesn't help me much right now)

**Comment by timoxley** [comment] 2017-09-14 11:06
Member expressions indentation is a dupe of https://github.com/standard/standard/issues/628 and both generally covered by https://github.com/standard/standard/issues/735. Suggest closing.

**Closed** 2017-09-18 09:09 UTC

**Comment by chee** [comment] 2017-09-18 10:44
thanks, tim
