### ISSUE TITLE
Template string indentation style

### ISSUE THREAD

**Issue by wll8** [standard/standard#1138] opened 2018-05-21 07:44 UTC
**What version of standard?**
``` json
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
  }
``` 

**What operating system, Node.js, and npm version?**
operating system `Mac OS X 10.13.1`
node `v8.9.4`
npm `v5.6.0`

**What did you expect to happen?**
I hope the style:
``` js
const fHtml = formatHtml(`
  <style>
    ${
        getText('./css1.css')
      + getText('./css2.css')
    }
  </style>
`)
``` 

**What actually happened?**
Get error: 
`[eslint] Expected indentation of 2 spaces but found 12. (indent)`

Do I have to use the following style?
``` js
const fHtml = formatHtml(`
  <style>
    ${getText('./css1.css') + getText('./css2.css')}
  </style>
`)
``` 

``` js
const fHtml = formatHtml(`
  <style>
    ${
  getText('./css1.css')
+ getText('./css2.css')
}
  </style>
`)
```

**Comment by LinusU** [comment] 2018-05-21 12:19
I think that the problem is that you are basically writing JavaScript that looks like this:

```js
const text = (
        getText('./css1.css')
      + getText('./css2.css')
    )
```

I don't have a strong opinion here, but I might be leaning towards not changing anything 🤔 

btw. you could do it like this, no?

```js
const fHtml = formatHtml(`
  <style>
    ${getText('./css1.css')}
    ${getText('./css2.css')}
  </style>
`)
```

**Comment by wll8** [comment] 2018-05-21 15:06
@LinusU 

## 1
``` js
const text = (
    getText('./css1.css')
  + getText('./css2.css')
)
``` 
It can indeed be done. But I don't want to write more code and variables.
Just like jsx , why not use expressions? :smile:

## 2

``` js
const fHtml = formatHtml(`
  <style>
    ${getText('./css1.css')}
    ${getText('./css2.css')}
  </style>
`)
``` 
:sunglasses: I think they are different, like...

`${1}   ${2}`  and `${1 + 2}`

## 3
I think this is where we should discuss. :pensive:

![image](https://user-images.githubusercontent.com/28223260/40313889-72d5a6b2-5d49-11e8-9c6d-2d60d46f3bbf.png)

**Comment by LinusU** [comment] 2018-05-21 16:37
The `1` wasn't meant as a suggestion, it was meant to show why your code is rejected by standard. My point was to illustrate that you probably wouldn't have thought it was strange that standard didn't like:

```js
const text = (
        getText('./css1.css')
      + getText('./css2.css')
    )
```

The `2` was meant as a suggestion for your specific case, as it seemed like you were outputting text...

-----

I could potentially see that this should be legal though:

```js
const text = `
  <style>
    ${
      foo() +
      bar()
    }
  </style>
`
```

although to be honest, I'm not 100% sure that I think it looks that good 🤔 

It's hard to think about without a valid use-case, I can't see a scenario where you would want to do arithmetic addition on a long list of variables inside a template string...

**Comment by wll8** [comment] 2018-05-22 05:00
@LinusU 
Ok. I also don't want to use arithmetic addition. I just think it's an example to illustrate that `${a} ${b}` and `${a + b}` are different.

I am focused on explaining it:
**`${a} ${b}` does not ignore indentation.**

The `1` is indeed a scheme. Maybe I should use it.

Thank you。

**Comment by feross** [comment] 2018-05-23 00:49
The JSX indent rules have some bugs with edge cases like this, in my experience.

@wll8 I think for your use case, @LinusU's suggestion works perfectly fine. Even though, you're technically right that `${a} ${b}` and `${a + b}` are different, if `${a} ${b}` works for your use case, then why not use it?

I'm going to try to change rules in standard v12 to make JSX indentation work better, if it's at all possible. In the meantime, I think we can close this issue.

**Closed by feross** 2018-05-23 00:49 UTC
